### ISSUE TITLE
Mystery failure trying to run tests after compilation

### ISSUE THREAD

**Issue by dtonhofer** [MiniZinc/libminizinc#504]
I'm trying to compile libminizin and have apparently succeeded.

Still, running the tests is a chore. I haven't found out how to tell the system where my chuffed and gecode executables are but apart from that, running the tests fails mysteriously:

```
pytest --solvers gecode,chuffed
```

mostly yields the error

```
E   TypeError: argument of type 'NoneType' is not iterable
```

This is due to the fact that in `conftest.py` at line 174:

```
        if self.config.getoption("--solvers") is not None:
            self.allowed = [
                x.strip() for x in self.config.getoption("--solvers").split(",")
            ]
            self.allowed = [x for x in self.allowed if x in suite.solvers]  #### HERE
        else:
            self.allowed = suite.solvers

        if not self.solver_allowed(solver):
            self.add_marker(
                pytest.mark.skip("skipping {} not in {}".format(solver, self.allowed))
            )
```

The value for `suite.solvers` is `None`. 

This probably means that something is missing in a config file, but I have no clue what is going on. In other words: the test script should tell me what's up.

Note: So far I have managed to compile _libminizinc_, _gecode_ and _chuffed_ but it is unclear to me how to make them aware of each other or how to make the system aware that they exist, which may have something to do with the problem.

**Comment by cyderize** [comment]
Which branch are you compiling? I think that bug may have already been fixed in the `develop` branch.

The way to make MiniZinc aware of solvers is to place a [solver configuration file](https://www.minizinc.org/doc-2.5.5/en/fzn-spec.html#solver-configuration-files) somewhere in MiniZinc's solver search path. Both Chuffed and Gecode come with the required configuration files (at least in their `develop` branches).

You may have to add `<YOUR_SOLVER_INSTALL_PREFIX>/share/minizinc/solvers/` to the `MZN_SOLVER_PATH` environment variable if the solvers haven't been installed in the same place as MiniZinc.

**Comment by dtonhofer** [comment]
Thank you. Currently compiling the 2.5.5 tag. Ok, lets try this setup.

**Comment by dtonhofer** [comment]
Update: Running tests with "libminizinc" compiled from the "develop" branch.

Better, but still getting errors:

14 failed, 401 passed, 608 skipped, 4 warnings in 90.66s (0:01:30)

**Comment by guidotack** [comment]
Some tests require libminizinc to be compiled against Gecode. Can you check if the 14 failures are all to do with the regular constraint and checker models (the error messages should say that those are only supported if Gecode was available during compilation). I think 14 sounds about the number I’d expect without Gecode.

**Comment by Dekker1** [comment]
Since no concrete problems seem to be signalled in this topic and all test cases pass in our CI, I will close this issue

**Comment by dtonhofer** [comment]
Thanks. I will still undig this and report back on the type of failures.

**Comment by dtonhofer** [comment]
Some more info:
 
**minizinc release + gecode release**  or **minizinc release + gecode devel**

We get 373 errors of the kind "E   TypeError: argument of type 'NoneType' is not iterable"
These are solved when upgrading to the devel version.

**minizinc devel + gecode release**

We get;

"15 failed, 403 passed, 610 skipped, 4 warnings in 92.13s (0:01:32)"

due to 

```
E             message: "/usr/local/minizinc/libminizinc_devel_with_gecode_release/share/minizinc/std/nvalue_fn.mzn:7.57-67:\nMiniZinc:
E               type error: no function or predicate with this signature found: `nvalue(var int,array[$_]
E               of var int)'\nCannot use the following functions or predicates with the same identifier:\nfunction
E               var int : nvalue(array [$X] of var int: x);\n    (requires 1 argument, but 2 given)\npredicate
E               nvalue(var int: n,array [int] of var int: x);\n    (argument 2 expects type array[int]
E               of var int, but type array[$_] of var int given)\nFile fragment:\n6: function var
E               int: nvalue(array[$X] of var int: x) =\n7:   let { var 0..length(x): n::is_defined_var;
E               constraint nvalue(n,x)::defines_var(n); } in n;\n    
```

This is also expected with the combination **minizinc devel + gecode release** - upgrade gecode.

**minizinc devel + gecode devel**

Should be the best. 

However, the tests fail because Python attempts to create a cache in the installation directory, to which it has no access:

```
PytestCacheWarning: could not create cache path /usr/local/minizinc/libminizinc/bin/.pytest_cache/v/cache/nodeids
/home/rost/.local/lib/python3.9/site-packages/_pytest/cacheprovider.py:428
```

In this latter case, something needs to be changed.

**Comment by Dekker1** [comment]
We only test for the last case, if you want to test with MiniZinc Release, then you have to still take the development version of Gecode (or even the development version of Gecode at the time of release).

When taking both development versions this should work. The problem seems to be in the way that you run PyTest, not the tests themselves. You can see how the tests are run in the CI by looking at the CI file here: https://github.com/MiniZinc/libminizinc/blob/master/.gitlab-ci.yml#L153-L179.

If the problem is only the cache directory, then you can have a look at changing its location using the `cache_dir` configuration option: https://docs.pytest.org/en/latest/reference/reference.html#confval-cache_dir
