### ISSUE TITLE
Infeasible solution returned (related to issue 666)

### ISSUE THREAD

**Issue by anonymous192837** [MiniZinc/libminizinc#683]
Thanks for the fix of #666. I tested with 2.7.3 but the original model there still gives solutions with `c = 2` on Gecode and HiGHS. I think the simplified model turned out to be a different bug, sorry.

**Comment by Dekker1** [comment]
Resolved by c8fdf078b25b43bbb1553a1cc6d4b96931d3da9c

**Comment by anonymous192837** [comment]
Thanks again for the swift fix. I hate to be persistent, but the issue is not completely fixed I'm afraid:

```
var opt 1..1: x ::output;

constraint if absent(x) then x = 1 endif;
constraint if x = 1 then false endif;

solve satisfy;
```

This model is considered satisfiable with `-Glinear`.

**Comment by Dekker1** [comment]
I'm happy your persistent. We'd of course rather be aware of any issues in the compiler. I've created a separate issue for the model, so the issue is easier to name.
